#pragma once

using namespace ATL;

template <class T>
class CProxy_IATLActivexControlEvents : public IConnectionPointImpl<T, &__uuidof(_IATLActivexControlEvents), CComDynamicUnkArray>
{
	// WARNING: This class may be regenerated by the wizard
public:
};
